config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'login', to: 'static_pages#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QuizApp
    = csrf_meta_tags
    = csp_meta_tag
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/static_pages/home.html.haml
.jumbotron
  %h1.animate__animated.animate__rotateIn.text-center
    Welcome to Quiz App
.row
  .col
    .card{style: "width: 18rem;"}
      .card-body
        %h5.card-title Want to have new Quiz Competition?
        %h6.card-subtitle.mb-2.text-muted A new Quiz registration
        %p.card-text Please follow the link and create a new quiz
        %a.card-link{href: "#"} New Quiz Competition
        -# %a.card-link{href: "#"} Another link
  .col
    .card{style: "width: 18rem;"}
      .card-body
        %h5.card-title Already have a Quiz Competition?
        %h6.card-subtitle.mb-2.text-muted Ongoing Quiz
        %p.card-text Just go to your Quiz through the link.
        .card-link
          = link_to "Your Quiz", login_url
        -# %a.card-link{href: "#"} Another link
  .col
    .card{style: "width: 18rem;"}
      .card-body
        %h5.card-title Want to see archived Quiz Competitions?
        %h6.card-subtitle.mb-2.text-muted Archived Quiz
        %p.card-text Please click on the link below and get your archived Quiz!
        %a.card-link{href: "#"} Your archived Quizzes
        -# %a.card-link{href: "#"} Another link